---

- hosts: all
  become: true
  tasks:

  - name: Install apache webserver package
    yum:
      update_cache: yes 

  - name: Update apache webserver package
    yum:
      name: httpd 
      state: latest

  - name: Start web server
    service:
      name: httpd
      state: started
